version: "3.8"

services:
  app:
    build:
      context: app
      target: dev
    network_mode: "host"
    volumes:
      - "./app:/app"

  api:
    build:
      context: api
      target: dev
    network_mode: "host"
    volumes:
      - "./api:/app"

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db

volumes:
  db:
