version: "3.8"

services:
  api:
    hostname: api
    build:
      context: .
      target: prod
      args:
        VITE_API_URI: ${VITE_API_URI}
        VITE_STRIPE_PK: ${VITE_STRIPE_PK}
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mongo
      - postgres
    networks:
      - traefik
    labels:
      - "traefik.http.routers.vuestone.rule=Host(`vuestone.quozul.dev`)"
      - "traefik.http.routers.vuestone.tls=true"
      - "traefik.http.routers.vuestone.tls.certresolver=myresolver"
      - "traefik.http.services.vuestone.loadbalancer.server.port=80"
      - "traefik.http.routers.vuestone.tls.domains[0].main=vuestone.quozul.dev"

  postgres:
    hostname: postgres
    extends:
      file: docker-compose.dev.yml
      service: postgres
    networks:
      - traefik

  mongo:
    hostname: mongo
    extends:
      file: docker-compose.dev.yml
      service: mongo
    networks:
      - traefik

volumes:
  db:
  mongo:

networks:
  traefik:
    external: true
    name: traefik
