version: "3.8"

services:
  app:
    build:
      context: app
      target: dev
    env_file:
      - ./app/.env
    network_mode: "host"
    volumes:
      - "./app:/app"

  api:
    build:
      context: api
      target: dev
    env_file:
      - ./api/.env
    network_mode: "host"
    volumes:
      - "./api:/app"

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo:/data/db

volumes:
  db:
  mongo: