version: "3.8"

services:
  api:
    build:
      context: .
      target: prod
      args:
        VITE_API_URI: ${VITE_API_URI}
        VITE_STRIPE_PK: ${VITE_STRIPE_PK}
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mongo
      - postgres
    labels:
      - "traefik.http.routers.vuestone.rule=Host(`vuestone.quozul.dev`)"
      - "traefik.http.routers.vuestone.tls.certresolver=myresolver"
      - "traefik.http.routers.vuestone.tls.domains[0].main=vuestone.quozul.dev"
      - "traefik.http.routers.vuestone.tls=true"
      - "traefik.http.services.vuestone.loadbalancer.server.port=8080"

  postgres:
    extends:
      file: docker-compose.dev.yml
      service: postgres

  mongo:
    extends:
      file: docker-compose.dev.yml
      service: mongo

volumes:
  db:
  mongo:

networks:
  default:
    external: true
    name: traefik
