version: "3.8"

services:
  api:
    build:
      context: .
      target: prod
      args:
        VITE_API_URI: ${VITE_API_URI}
        VITE_STRIPE_PK: ${VITE_STRIPE_PK}
        VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    ports:
      - "8080:8080"
    env_file: .env
    restart: always
    depends_on:
      - mongo
      - postgres

  fixtures:
    build:
      context: .
      target: fixtures
      args:
        VITE_API_URI: ${VITE_API_URI}
        VITE_STRIPE_PK: ${VITE_STRIPE_PK}
        VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    restart: no
    depends_on:
      - mongo
      - postgres
    env_file: .env

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - "db:/var/lib/postgresql/data"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo:/data/db

volumes:
  db:
  mongo:
