version: "3.8"

services:
  app:
    build:
      context: app
      target: prod
      args:
        VITE_API_URI: ${VITE_API_URI}
        VITE_STRIPE_PK: ${VITE_STRIPE_PK}
    labels:
      - "traefik.http.routers.vuestone.rule=Host(`vuestone.quozul.dev`)"
      - "traefik.http.routers.vuestone.tls=true"
      - "traefik.http.routers.vuestone.tls.certresolver=myresolver"
      - "traefik.http.services.vuestone.loadbalancer.server.port=80"
      - "traefik.http.routers.vuestone.tls.domains[0].main=vuestone.quozul.dev"
    env_file: .env
    #ports:
    #  - "8089:80"
    networks:
      - traefik

  api:
    build:
      context: api
      target: prod
    expose:
      - "8080:8080"
    env_file: .env

  postgres:
    extends:
      file: docker-compose.dev.yml
      service: postgres

  mongo:
    extends:
      file: docker-compose.dev.yml
      service: mongo

volumes:
  db:
  mongo:

networks:
  traefik:
    external: true
    name: traefik
