version: "3.8"

services:
  api:
    build:
      context: .
      target: prod
      args:
        VITE_API_URI: ${VITE_API_URI}
        VITE_STRIPE_PK: ${VITE_STRIPE_PK}
        VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    expose:
      - 8080
    env_file: .env
    depends_on:
      - mongo
      - postgres
    labels:
      - "traefik.http.routers.vuestone.rule=Host(`vuestone.quozul.dev`)"
      - "traefik.http.routers.vuestone.tls.certresolver=myresolver"
      - "traefik.http.routers.vuestone.tls.domains[0].main=vuestone.quozul.dev"
      - "traefik.http.routers.vuestone.tls=true"
      - "traefik.http.services.vuestone.loadbalancer.server.port=8080"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - "db:/var/lib/postgresql/data"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo:/data/db

volumes:
  db:
  mongo:

networks:
  default:
    external: true
    name: traefik
