version: "3.8"

services:
  app:
    build:
      context: app
      target: prod
    ports:
      - "80:80"

  api:
    build:
      context: api
      target: prod
    ports:
      - "8080:8080"

  postgres:
    extends:
      file: docker-compose.dev.yml
      service: postgres

  mongo:
    extends:
      file: docker-compose.dev.yml
      service: mongo

volumes:
  db:
