version: "3.8"

services:
  app:
    build:
      context: app
      target: dev
    network_mode: "host"
    volumes:
      - "./app:/app"

  api:
    build:
      context: api
      target: dev
    network_mode: "host"
    volumes:
      - "./api:/app"
